import styles from "./Footer.module.css";

const Footer = () => {
  return (
    <div className={styles.footer}>
      <div className={styles.footerContainer}>
        <p>Images are AI generated by ChatGPT</p>
        <p>
          © 2025 "The Fruiting Forest" by Martinus Aamot Dahl. All rights
          reserved.
        </p>
      </div>
    </div>
  );
};

export default Footer;
